[package]
name = "git-open"
version = "0.0.1"
edition = "2018"
readme = "README.md"
license = "MIT"
keywords = ["git"]
authors = ["Jesus Galvan <jesgvn@gmail.com>"]
repository = "https://github.com/jsgv/git-open"
homepage = "https://github.com/jsgv/git-open"
categories = ["command-line-utilities"]

[[bin]]
name = "git-open"

[lib]
name = "gitopen"
doctest = false

[dependencies]
clap = { version = "~2.33.0", features = ["yaml"] }
git2 = "0.13.20"
open = "1"
regex = "1"
