name: CD Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar -czvf git-open-${{ matrix.target }}.tar.gz git-open

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/git-open-${{ matrix.target }}.tar.gz
